# ===================================================================
# CONFIGURACI�N DE LA APLICACI�N Y RUTA DE LA API
# ===================================================================
spring.application.name=tableros-kanban

# Definimos la base de la API REST (igual que ten�as ${tpv.private.api} en el TPV)
# Esto har� que tus endpoints de tableros respondan en: http://localhost:8080/api/v1/tableros
tableros.private.api=/api/v1

# Puerto del servidor embebido de Spring (por si pruebas la API REST con Postman o el navegador)
server.port=8080

# ===================================================================
# CONFIGURACI�N DE LA BASE DE DATOS (H2 en memoria)
# ===================================================================
# Usamos H2 en memoria RAM (ideal para la pr�ctica porque no requiere instalar nada)
spring.datasource.url=jdbc:h2:file:./data/kanbandb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Activar la consola web de H2 para que pod�is ver las tablas desde el navegador
# Entrando a http://localhost:8080/h2-console con la URL de arriba podr�is cotillear la BD
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================================================
# CONFIGURACI�N DE JPA / HIBERNATE
# ===================================================================
# update: Crea las tablas autom�ticamente al arrancar bas�ndose en vuestras @Entity de JPA
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Eclipse todas las sentencias SQL reales que ejecuta Spring por detr�s
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURACI�N DE LOGS
# ===================================================================
# Muestra tus mensajes de log.info tanto de la aplicaci�n como del dominio
logging.level.es.um.pds.tableros=INFO
logging.level.org.springframework.web=INFO


#correo# Configuraci�n del servidor de correo SMTP de Google
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=guillermofparralopez@gmail.com
spring.mail.password=oqmmgmrthdwifmxb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=guillermofparralopez@gmail.com
spring.mail.properties.mail.from=guillermofparralopez@gmail.com
spring.mail.properties.mail.smtp.localhost=localhost